name: FibCalc

on:
  push:
    branches: [ main ]
    tags: [ v* ]
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      #Konfiguracja kontroli wersji Semver
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{secrets.DOCKER_HUB_USERNAME}}/zadanie1, ghcr.io/${{ github.actor }}/zadanie1
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      #Skonfigurowanie dockera + buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      
      #Instalacja QEMU      
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0

      #Logowanie do DockerHub  
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      #Logowanie do GitHub Pachages   
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GIT }}
          
      #Zbudowanie i wypchniecie obrazu na Dockerhuba i ghcr
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,src=docker.io/${{secrets.DOCKER_HUB_USERNAME}}/zadanie1:cache
          cache-to: type=registry,dest=docker.io/${{secrets.DOCKER_HUB_USERNAME}}/zadanie1:cache,mode=max
          platforms: linux/amd64, linux/arm64
          context: .
          file: Dockerfile
          buildkit: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
